version: "3.9"

services:
  mysql:
    container_name: "mysql"
    image: "mysql:8.0"
    platform: "linux/amd64"
    restart: "always"
    command: "mysqld --character-set-server=utf8mb4"
    networks:
      - "bank-user"
    volumes:
      - "./mysql_data/data:/var/lib/mysql"
      - "./mysql_data/config:/etc/mysql/conf.d"
      - "./mysql_data/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "jawn_bank"
      MYSQL_USER: "jawn"
      MYSQL_PASSWORD: "jawn"
    #      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD"]
      interval: 2s
      timeout: 20s
      retries: 10

networks:
  bank-user:
    name: bank-user
